### ISSUE TITLE
Current state

### ISSUE THREAD

**Issue by astrojuanlu** [ipython/jsplugins#1]
I was about to report the failure of d3graph under IPython 1.0, but as the last commit is 9 months old maybe I'm missing some information about the current (or future) state of these plugins. Are they still maintained and supposed to work? Or maybe is there any replacement in the works for upcoming versions of IPython?

**Comment by ellisonbg** [comment]
We will soon start to work on some new stuff related to this - but in a
slightly different direction than the existing jsplugins.  Eventually we
will update the d3graph example.  Probably 2-3 months away.

Chers,

Brian

On Fri, Aug 16, 2013 at 6:31 AM, Juan Luis Cano Rodríguez <
notifications@github.com> wrote:

> I was about to report the failure of d3graph under IPython 1.0, but as the
> last commit is 9 months old maybe I'm missing some information about the
> current (or future) state of these plugins. Are they still maintained and
> supposed to work? Or maybe is there any replacement in the works for
> upcoming versions of IPython?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ipython/jsplugins/issues/1
> .

## 

Brian E. Granger
Cal Poly State University, San Luis Obispo
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by astrojuanlu** [comment]
Perfect, thanks for clarifying! I'm leaving the issue open unless you consider it better to close it.

**Comment by astrojuanlu** [comment]
Got it, you were referring to IPython/IPython#2802 I guess.

**Comment by ellisonbg** [comment]
That issue is more related to our older plans - we will be updating it soon
to reflect the new work.  In the meantime here is a hackpad we started at
our dev meeting:

https://hackpad.com/IPython-Interactive-JavaScript-Widget-Design-jRD6dHFt5I8

On Sat, Aug 17, 2013 at 9:57 AM, Juan Luis Cano Rodríguez <
notifications@github.com> wrote:

> Got it, you were referring to IPython/IPython#2802https://github.com/ipython/ipython/issues/2802I guess.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ipython/jsplugins/issues/1#issuecomment-22815410
> .

## 

Brian E. Granger
Cal Poly State University, San Luis Obispo
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by lisabang** [comment]
How are things going with this?  The hackpad document is pretty intriguing.

**Comment by ellisonbg** [comment]
The work is going very well.  Here is the pull request we are working on:

https://github.com/ipython/ipython/pull/4374

Should be merged in the next month and released in IPython 2.0 (Jan).

On Tue, Dec 10, 2013 at 11:09 PM, lisabang notifications@github.com wrote:

> How are things going with this? The hackpad document is pretty intriguing.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ipython/jsplugins/issues/1#issuecomment-30299168
> .

## 

Brian E. Granger
Cal Poly State University, San Luis Obispo
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by Carreau** [comment]
Closing as the jsplugin repo have never really take off.
