### ISSUE TITLE
pytutor, ImportError: cannot import name publish_json

### ISSUE THREAD

**Issue by cypreess** [ipython/jsplugins#2]
Using ipython 1.1.0 and master branch of jsplugin.

Trying importing pytutor resulting 

```
>>> import pytutor
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/cypreess/dev/jsplugins/pytutor/python/pytutor.py", line 27, in <module>
    from IPython.core.displaypub import publish_json
ImportError: cannot import name publish_json
```

**Comment by toinfty** [comment]
publish_json no longer exists in the IPython.core.displaypub module. Can somebody fix it?

**Comment by skyuuka** [comment]
Have it been solved? I still have the same issue. Hope anyone can help me out.

**Comment by Carreau** [comment]
Closing as the jsplugin repo have never really take off.
